#!/bin/bash

SCRIPT_NAME_PREFIX="#####"
SCRIPT_BODY_PREFIX=""

: '
 Arguments received:
 - $1 : the name of the script
 - $2 : the description of the task (use markdown syntax)

 This utility does the following:
 - creates a script name $1
 - adds a bash shebang on the first line of the script
 - adds execute permission to the script
 - adds description of the script to README.md
 creates a script and adds description of the script to README.md
 The default format for writing description is

 ##### Script Name
 script description
'

echo "#!/bin/bash" > $1
chmod u+x $1
echo "$SCRIPT_NAME_PREFIX $1
$2" >> README.md
